name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Use your preferred Node.js version

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install  # This is the key step to install Playwright browsers

    - name: Run Playwright Tests
      run: npx playwright test arbree/swag.test.ts --headed
